targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/model/**/*.dart
      freezed:
        generate_for:
          - lib/src/model/**/*.dart
        options:
          from_json: false
          to_json: false
      riverpod_generator:
        generate_for:
          - lib/src/localizations.dart
          - lib/src/theme.dart
          - lib/src/model/**/*.dart
          - lib/src/network/*.dart
          - lib/src/db/*.dart
          - lib/src/**/*_providers.dart
